[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"
description = "My attempt at the Advent of Code 2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
